name: Calico
description: |
  A Pure Layer 3 Approach to Virtual Networking for Highly Scalable Data Centers
version: v0.23.0        # Keep this in sync with calico/node tag version
category: Networking
projectURL: https://www.projectcalico.org/
license: Apache License, Version 2.0
labels:
  io.rancher.certified: rancher
