version: '2'
services:
  calico:
    cap_add:
      - NET_ADMIN
    image: calico/node:v0.23.0
    network_mode: host
    depends_on:
      - calico-etcd
    labels:
      io.rancher.sidekicks: cni-driver
      io.rancher.scheduler.global: 'true'
      io.rancher.container.dns: 'true'
    volumes:
      - /var/run/calico:/var/run/calico:rw
      - /var/log/calico:/var/log/calico:rw
    environment:
      - ETCD_ENDPOINTS=http://calico-etcd:2379
  cni-driver:
    privileged: true
    image: calico/cni:v1.4.3
    command: sh
    tty: true
    network_mode: host
    pid: host
    labels:
      io.rancher.network.cni.binary: 'calico'
      io.rancher.container.dns: 'true'
  calico-etcd:
    image: quay.io/coreos/etcd:v3.0.14
    network_mode: host
    labels:
      io.rancher.container.dns: 'true'
    command:
      - etcd
      - -advertise-client-urls
      - http://0.0.0.0:2379,http://0.0.0.0:4001
      - -listen-client-urls
      - http://0.0.0.0:2379,http://0.0.0.0:4001
